### ISSUE TITLE
Recognize构造函数加载模型失败

### ISSUE THREAD

**Issue by mhsszm** [GRAYKEY/mobilefacenet_android#12]

**Comment by ZivenMan** [comment]
注意，如果你是用android 10测试，会存在读取不到模型文件的问题，从而导致加载模型失败。那是因为Android Q文件存储机制修改成了沙盒模式，操作拍照，或者上传，报错，打日志，获取相片的路径为空，解决办法：
在AndroidManifest.xml 里的application中添加 android:requestLegacyExternalStorage=“true” 临时解决。可以兼容到Android 11。或者targetsdk 降低到29以下。参见：https://blog.csdn.net/yhx956058885/article/details/107359184/
