### ISSUE TITLE
下面这行注释有没有好的解释，对齐需要做哪些，如果不缩放如何使用？

### ISSUE THREAD

**Issue by wangxm345566462** [GRAYKEY/mobilefacenet_android#15]
下面这行注释有没有好的解释，对齐需要做哪些，如果不缩放如何使用？

  //没进行对齐操作，且以下对图像缩放的操作方法对结果影响较大。可改进空间很大，有能力的自己改改

**Comment by mmabluesky** [comment]
找到五个关键点，根据左右眼的夹角 ，做仿射变换
