### ISSUE TITLE
请问识别用的模型文件是哪里来的？

### ISSUE THREAD

**Issue by ghost** [GRAYKEY/mobilefacenet_android#3]
assets里面的用于识别的模型文件是自己训练的还是别的什么地方的？

**Comment by GRAYKEY** [comment]
自己训练的。github搜下mobilefacenet有很多教程

**Comment by ghost** [comment]
@GRAYKEY 谢谢 看到代码里bitmap数据做色彩转换的时候从RGBA到RGB，帮助很大，之前一直出错，看到你的代码才发现问题所在。
